services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cakeshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"


  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_JWT_EXPIRATION: ${REFRESH_JWT_EXPIRATION}
      ACCESS_JWT_EXPIRATION: ${ACCESS_JWT_EXPIRATION}

      REDIS_HOST: redis
      REDIS_PORT: 6379

      RESEND_API_KEY: ${RESEND_API_KEY}


volumes:
  postgres_data: