export enum ErrorCodeEnum {

    // AUTH
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    TOKEN_EXPIRED = "TOKEN_EXPIRED",

    // USER
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_DISABLED = "USER_DISABLED",
    USER_DELETED = "USER_DELETED",
    USER_NOT_VERIFIED = "USER_NOT_VERIFIED",
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
    USER_NOT_ADMIN = "USER_NOT_ADMIN",
    USER_ALREADY_ADMIN = "USER_ALREADY_ADMIN",
    USER_ACTIVATED = "USER_ACTIVATED",
    WRONG_PASSWORD = "WRONG_PASSWORD",

    // ADMIN
    USER_ACTION_FORBIDDEN = "USER_ACTION_FORBIDDEN",

    // PRODUCT
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
    PRODUCT_ALREADY_EXISTS = "PRODUCT_ALREADY_EXISTS",
    PRODUCT_INVALID_PRICE = "PRODUCT_INVALID_PRICE",

    // ORDER
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND",
    ORDER_FINISHED = "ORDER_FINISHED",

    // CART
    INVALID_QUANTITY = "INVALID_QUANTITY",
    CART_EMPTY = "CART_EMPTY",

    // DTOs
    VALIDATION_ERROR = "VALIDATION_ERROR",

    // NAMES
    INVALID_NAME = "INVALID_NAME",
    NAME_ALREADY_EXISTS = "NAME_ALREADY_EXISTS",

    // EMAIL
    INVALID_EMAIL = "INVALID_EMAIL",

    // FIELDS OF THE REQUEST
    ONE_FIELD_REQUIRED = "ONE_FIELD_REQUIRED",

    // REQUESTS
    MANY_REQUESTS = "MANY_REQUESTS"
    
}