package br.com.davi.spring_boot_first.enums;


public enum ErrorCodeEnum {

    // AUTH
    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,

    // USER
    USER_NOT_FOUND,
    USER_DISABLED,
    USER_DELETED,
    USER_NOT_VERIFIED,
    EMAIL_ALREADY_EXISTS,
    USER_NOT_ADMIN,
    USER_ALREADY_ADMIN,
    USER_ACTIVATED,
    WRONG_PASSWORD,

    // ADMIN
    USER_ACTION_FORBIDDEN,

    // PRODUCT
    PRODUCT_NOT_FOUND,
    PRODUCT_ALREADY_EXISTS,
    PRODUCT_INVALID_PRICE,

    // ORDER
    ORDER_NOT_FOUND,
    ORDER_FINISHED,

    // CART
    INVALID_QUANTITY,
    CART_EMPTY,

    // DTOs
    VALIDATION_ERROR,

    // NAMES
    INVALID_NAME,
    NAME_ALREADY_EXISTS,

    // EMAIL
    INVALID_EMAIL,

    // FIELDS OF THE REQUEST
    ONE_FIELD_REQUIRED,

    // REQUESTS
    MANY_REQUESTS

}